services:
  - type: web
    name: hng_api
    env: python3
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn hng_api.wsgi:application"
    envVars:
      - key: 'django-insecure-#z3dy)q0qnl14ksrm6b@zdo3#bc43^5v^!unll_n1)p60i$%1('
        sync: false
      - key: DEBUG
        value: false
      
