services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
